"""add_pin_hash_and_is_visible_to_rooms

Revision ID: a231a99ac728
Revises: 41a412e9f427
Create Date: 2026-05-24 15:37:25.423849

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a231a99ac728'
down_revision: Union[str, Sequence[str], None] = '41a412e9f427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('rooms', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_visible')
    op.drop_column('rooms', 'pin_hash')
    # ### end Alembic commands ###
