"""add queue_votes and queue_histories

Revision ID: cbd98fc7226e
Revises: 14fc7043255c
Create Date: 2026-05-02 23:45:18.818480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbd98fc7226e'
down_revision: Union[str, Sequence[str], None] = '14fc7043255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('queue_item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_item_id'], ['queue_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_item_id', 'user_id', name='uq_queue_item_user_vote')
    )
    # SQLite requires batch mode for ALTER TABLE with foreign keys
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_users_room_id', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_room_id', type_='foreignkey')
        batch_op.drop_column('room_id')
    op.drop_table('queue_votes')
    op.drop_table('queue_histories')
    # ### end Alembic commands ###
